### ISSUE TITLE
How to update the schema?

### ISSUE THREAD

**Issue by jacobsapps** [aws-samples/aws-serverless-app-with-aurora-and-python-sql-alchemy-example#3]
I've been working on a python backend application based on the architecture you taught me in this tutorial. 

I've had difficulty whenever I needed to update the schema however: 

When I update the schema (by re-deploying it in SAM or via my CI), the CloudFormation stack fails to update because the API stack is dependent on it. What seemed to work was deleting the API stack each time I deployed, but of course this is not sustainable.

I tried to address this by merging the schema and API into one stack, however the custom Lambda trigger that actually deployed the schema didn't seem to work here.

Do you have advice on how I would go about updating the schema? 

Thank you

**Comment by marcilio** [comment]
Hi Jacob,

The API stack requires two values that are exported by the Aurora VPC stack: 
- SecretRotationLambdaSecurityGroup
- SubnetsPrivate

These values are currently being exported by the Aurora VPC stack and imported into the API stack. 

What you could do to break the stack dependency is:

1) Remove input parameter `AuroraVPCStackName` from the API stack
2) Create two new input parameters on the API stack: 
- SecretRotationLambdaSecurityGroup
- SubnetsPrivate

These way you'd break the export/import dependency and manually enter the values for those parameters if you need to update the API stack.

Let me know how it goes.

**Comment by jacobsapps** [comment]
Hi @marcilio,

Thank you for sending this over. I actually managed to get it working by merging the two template.yaml files, which meant only one combined deployment was required when I ran the code on my CI. 

Best wishes,

Jacob

**Comment by srijitm** [comment]
Issue resolved.

**Comment by luis-echegaray** [comment]
how does someone update the schema. I usually just blow everything away and re-create.
